/**
 * BDII / GLUE2 SNAPSHOT
 * ---------------------
 * The live top-BDII (ldap://sbdii.ui.savba.sk:2170, base o=glue) speaks raw
 * LDAP on port 2170. This runtime can only open outbound HTTP(S), so the BDII
 * adapter reads a captured GLUE2 snapshot instead of querying LDAP live.
 *
 * Everything else in the pipeline treats this adapter exactly like the live
 * ones; the provider is reported with mode = "snapshot" and the UI labels it
 * as such. Point BDII_MODE at an HTTPS LDAP bridge to make it live.
 *
 * Attribute names follow the GLUE2 LDAP schema:
 *   GLUE2DomainID, GLUE2DomainDescription, GLUE2LocationCountry,
 *   GLUE2LocationLatitude, GLUE2LocationLongitude, GLUE2ServiceID,
 *   GLUE2EndpointURL, GLUE2EndpointImplementationName,
 *   GLUE2EndpointImplementationVersion, GLUE2EndpointHealthState
 */

export interface Glue2Entry {
  GLUE2DomainID: string;
  GLUE2DomainDescription: string;
  GLUE2LocationCountry: string;
  GLUE2LocationLatitude?: number;
  GLUE2LocationLongitude?: number;
  GLUE2ServiceID: string;
  GLUE2ServiceType: string;
  GLUE2EndpointURL: string;
  GLUE2EndpointImplementationName: string;
  GLUE2EndpointImplementationVersion: string;
  GLUE2EndpointHealthState: string;
}

export const BDII_SNAPSHOT_CAPTURED_AT = "2026-08-28T09:14:00Z";
export const BDII_BASE_DN = "o=glue";
export const BDII_HOST = "sbdii.ui.savba.sk";
export const BDII_PORT = 2170;

export const BDII_SNAPSHOT: Glue2Entry[] = [
  {
    GLUE2DomainID: "IISAS-Bratislava",
    GLUE2DomainDescription: "Institute of Informatics, Slovak Academy of Sciences",
    GLUE2LocationCountry: "Slovakia",
    GLUE2LocationLatitude: 48.171,
    GLUE2LocationLongitude: 17.07,
    GLUE2ServiceID: "sbdii.ui.savba.sk_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.ui.savba.sk:2170/Mds-Vo-name=IISAS-Bratislava,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "TU-Kosice",
    GLUE2DomainDescription: "Technical University of Kosice",
    GLUE2LocationCountry: "Slovakia",
    GLUE2LocationLatitude: 48.731,
    GLUE2LocationLongitude: 21.239,
    GLUE2ServiceID: "mon.grid.tuke.sk_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://mon.grid.tuke.sk:2170/Mds-Vo-name=TU-Kosice,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "prague_cesnet_lcg2_cert",
    GLUE2DomainDescription: "CESNET certification testbed, Prague",
    GLUE2LocationCountry: "Czech Republic",
    GLUE2LocationLatitude: 50.102,
    GLUE2LocationLongitude: 14.393,
    GLUE2ServiceID: "skurut16.cesnet.cz_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://skurut16.cesnet.cz:2170/mds-vo-name=prague_cesnet_lcg2_cert,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "praguelcg2",
    GLUE2DomainDescription: "Institute of Physics of the Czech Academy of Sciences, Prague",
    GLUE2LocationCountry: "Czech Republic",
    GLUE2LocationLatitude: 50.123,
    GLUE2LocationLongitude: 14.395,
    GLUE2ServiceID: "sbdii.farm.particle.cz_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.farm.particle.cz:2170/mds-vo-name=praguelcg2,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "CERN-PROD",
    GLUE2DomainDescription: "European Organization for Nuclear Research, Meyrin",
    GLUE2LocationCountry: "Switzerland",
    GLUE2LocationLatitude: 46.2331,
    GLUE2LocationLongitude: 6.0555,
    GLUE2ServiceID: "sbdii.cern.ch_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.cern.ch:2170/mds-vo-name=CERN-PROD,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "DESY-HH",
    GLUE2DomainDescription: "Deutsches Elektronen-Synchrotron, Hamburg",
    GLUE2LocationCountry: "Germany",
    GLUE2LocationLatitude: 53.5754,
    GLUE2LocationLongitude: 9.8798,
    GLUE2ServiceID: "grid-bdii.desy.de_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://grid-bdii.desy.de:2170/mds-vo-name=DESY-HH,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "FZK-LCG2",
    GLUE2DomainDescription: "Karlsruhe Institute of Technology, GridKa Tier-1",
    GLUE2LocationCountry: "Germany",
    GLUE2LocationLatitude: 49.0947,
    GLUE2LocationLongitude: 8.4341,
    GLUE2ServiceID: "site-bdii.gridka.de_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://site-bdii.gridka.de:2170/mds-vo-name=FZK-LCG2,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "INFN-T1",
    GLUE2DomainDescription: "INFN CNAF Tier-1, Bologna",
    GLUE2LocationCountry: "Italy",
    GLUE2LocationLatitude: 44.4949,
    GLUE2LocationLongitude: 11.3426,
    GLUE2ServiceID: "site-bdii.cr.cnaf.infn.it_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://site-bdii.cr.cnaf.infn.it:2170/mds-vo-name=INFN-T1,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "INFN-PISA",
    GLUE2DomainDescription: "INFN Sezione di Pisa",
    GLUE2LocationCountry: "Italy",
    GLUE2LocationLatitude: 43.7203,
    GLUE2LocationLongitude: 10.4083,
    GLUE2ServiceID: "sbdii.pi.infn.it_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.pi.infn.it:2170/mds-vo-name=INFN-PISA,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "IN2P3-CC",
    GLUE2DomainDescription: "CC-IN2P3, Villeurbanne",
    GLUE2LocationCountry: "France",
    GLUE2LocationLatitude: 45.7828,
    GLUE2LocationLongitude: 4.8656,
    GLUE2ServiceID: "cclcgtopbdii.in2p3.fr_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://cclcgtopbdii.in2p3.fr:2170/mds-vo-name=IN2P3-CC,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "GRIF",
    GLUE2DomainDescription: "Grille au service de la Recherche en Ile de France",
    GLUE2LocationCountry: "France",
    GLUE2LocationLatitude: 48.7,
    GLUE2LocationLongitude: 2.17,
    GLUE2ServiceID: "grid-bdii.grif.fr_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://grid-bdii.grif.fr:2170/mds-vo-name=GRIF,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "RAL-LCG2",
    GLUE2DomainDescription: "Rutherford Appleton Laboratory Tier-1, Didcot",
    GLUE2LocationCountry: "United Kingdom",
    GLUE2LocationLatitude: 51.5717,
    GLUE2LocationLongitude: -1.3128,
    GLUE2ServiceID: "site-bdii.gridpp.rl.ac.uk_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://site-bdii.gridpp.rl.ac.uk:2170/mds-vo-name=RAL-LCG2,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "UKI-LT2-IC-HEP",
    GLUE2DomainDescription: "Imperial College London, High Energy Physics",
    GLUE2LocationCountry: "United Kingdom",
    GLUE2LocationLatitude: 51.4988,
    GLUE2LocationLongitude: -0.1749,
    GLUE2ServiceID: "sbdii.grid.hep.ph.ic.ac.uk_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.grid.hep.ph.ic.ac.uk:2170/mds-vo-name=UKI-LT2-IC-HEP,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "NIKHEF-ELPROD",
    GLUE2DomainDescription: "Nikhef, National Institute for Subatomic Physics, Amsterdam",
    GLUE2LocationCountry: "Netherlands",
    GLUE2LocationLatitude: 52.3564,
    GLUE2LocationLongitude: 4.9515,
    GLUE2ServiceID: "bdii.nikhef.nl_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://bdii.nikhef.nl:2170/mds-vo-name=NIKHEF-ELPROD,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "SARA-MATRIX",
    GLUE2DomainDescription: "SURF, Amsterdam",
    GLUE2LocationCountry: "Netherlands",
    GLUE2LocationLatitude: 52.3565,
    GLUE2LocationLongitude: 4.9512,
    GLUE2ServiceID: "bdii.grid.sara.nl_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://bdii.grid.sara.nl:2170/mds-vo-name=SARA-MATRIX,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "pic",
    GLUE2DomainDescription: "Port d'Informacio Cientifica, Bellaterra",
    GLUE2LocationCountry: "Spain",
    GLUE2LocationLatitude: 41.5003,
    GLUE2LocationLongitude: 2.1105,
    GLUE2ServiceID: "site-bdii.pic.es_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://site-bdii.pic.es:2170/mds-vo-name=pic,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "IFCA-LCG2",
    GLUE2DomainDescription: "Instituto de Fisica de Cantabria, Santander",
    GLUE2LocationCountry: "Spain",
    GLUE2LocationLatitude: 43.4712,
    GLUE2LocationLongitude: -3.8043,
    GLUE2ServiceID: "sbdii.ifca.es_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.ifca.es:2170/mds-vo-name=IFCA-LCG2,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "NCG-INGRID-PT",
    GLUE2DomainDescription: "LIP Laboratorio de Instrumentacao e Fisica Experimental de Particulas, Lisbon",
    GLUE2LocationCountry: "Portugal",
    GLUE2LocationLatitude: 38.7566,
    GLUE2LocationLongitude: -9.1567,
    GLUE2ServiceID: "sbdii.ncg.ingrid.pt_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.ncg.ingrid.pt:2170/mds-vo-name=NCG-INGRID-PT,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "GR-07-UOI-HEPLAB",
    GLUE2DomainDescription: "University of Ioannina, HEP Laboratory",
    GLUE2LocationCountry: "Greece",
    GLUE2LocationLatitude: 39.6167,
    GLUE2LocationLongitude: 20.8397,
    GLUE2ServiceID: "sbdii.grid.uoi.gr_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.grid.uoi.gr:2170/mds-vo-name=GR-07-UOI-HEPLAB,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "HG-03-AUTH",
    GLUE2DomainDescription: "Aristotle University of Thessaloniki",
    GLUE2LocationCountry: "Greece",
    GLUE2LocationLatitude: 40.6316,
    GLUE2LocationLongitude: 22.9563,
    GLUE2ServiceID: "sbdii.grid.auth.gr_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.grid.auth.gr:2170/mds-vo-name=HG-03-AUTH,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "BUDAPEST",
    GLUE2DomainDescription: "Wigner Research Centre for Physics, Budapest",
    GLUE2LocationCountry: "Hungary",
    GLUE2LocationLatitude: 47.4794,
    GLUE2LocationLongitude: 18.9971,
    GLUE2ServiceID: "grid143.kfki.hu_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://grid143.kfki.hu:2170/mds-vo-name=BUDAPEST,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "TECHNION-LCG2",
    GLUE2DomainDescription: "Technion Israel Institute of Technology, Haifa",
    GLUE2LocationCountry: "Israel",
    GLUE2LocationLatitude: 32.7767,
    GLUE2LocationLongitude: 35.0231,
    GLUE2ServiceID: "sbdii.technion.ac.il_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.technion.ac.il:2170/mds-vo-name=TECHNION-LCG2,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "Taiwan-LCG2",
    GLUE2DomainDescription: "Academia Sinica Grid Computing Centre, Taipei",
    GLUE2LocationCountry: "Taiwan",
    GLUE2LocationLatitude: 25.0417,
    GLUE2LocationLongitude: 121.6144,
    GLUE2ServiceID: "sbdii.grid.sinica.edu.tw_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.grid.sinica.edu.tw:2170/mds-vo-name=Taiwan-LCG2,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.2",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "TRIUMF-LCG2",
    GLUE2DomainDescription: "TRIUMF, Vancouver",
    GLUE2LocationCountry: "Canada",
    GLUE2LocationLatitude: 49.2483,
    GLUE2LocationLongitude: -123.2318,
    GLUE2ServiceID: "sbdii.triumf.ca_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.triumf.ca:2170/mds-vo-name=TRIUMF-LCG2,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "BNL-ATLAS",
    GLUE2DomainDescription: "Brookhaven National Laboratory, Upton NY",
    GLUE2LocationCountry: "United States",
    GLUE2LocationLatitude: 40.8687,
    GLUE2LocationLongitude: -72.8862,
    GLUE2ServiceID: "sbdii.usatlas.bnl.gov_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.usatlas.bnl.gov:2170/mds-vo-name=BNL-ATLAS,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "Nebraska",
    GLUE2DomainDescription: "University of Nebraska-Lincoln, Holland Computing Center",
    GLUE2LocationCountry: "United States",
    GLUE2LocationLatitude: 40.8202,
    GLUE2LocationLongitude: -96.7005,
    GLUE2ServiceID: "sbdii.unl.edu_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.unl.edu:2170/mds-vo-name=Nebraska,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "MPPMU",
    GLUE2DomainDescription: "Max Planck Institute for Physics, Munich",
    GLUE2LocationCountry: "Germany",
    GLUE2LocationLatitude: 48.1497,
    GLUE2LocationLongitude: 11.5822,
    GLUE2ServiceID: "sbdii.rzg.mpg.de_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.rzg.mpg.de:2170/mds-vo-name=MPPMU,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
  {
    GLUE2DomainID: "JINR-LCG2",
    GLUE2DomainDescription: "Joint Institute for Nuclear Research, Dubna",
    GLUE2LocationCountry: "Russia",
    GLUE2LocationLatitude: 56.7461,
    GLUE2LocationLongitude: 37.1889,
    GLUE2ServiceID: "sbdii.jinr.ru_bdii_site",
    GLUE2ServiceType: "bdii_site",
    GLUE2EndpointURL: "ldap://sbdii.jinr.ru:2170/mds-vo-name=JINR-LCG2,o=grid",
    GLUE2EndpointImplementationName: "bdii",
    GLUE2EndpointImplementationVersion: "6.0.1",
    GLUE2EndpointHealthState: "ok",
  },
];
