/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiRouteImport } from './routes/api'
import { Route as DataRouteImport } from './routes/data'
import { Route as DataFlowRouteImport } from './routes/data-flow'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SitesIndexRouteImport } from './routes/sites.index'
import { Route as SitesIdRouteImport } from './routes/sites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DataFlowRoute = DataFlowRouteImport.update({
  id: '/data-flow',
  path: '/data-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SitesRoute,
} as any)
const SitesIdRoute = SitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRoute
  '/data': typeof DataRoute
  '/data-flow': typeof DataFlowRoute
  '/guide': typeof GuideRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/reconciliation': typeof ReconciliationRoute
  '/sites': typeof SitesRouteWithChildren
  '/sites/$id': typeof SitesIdRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRoute
  '/data': typeof DataRoute
  '/data-flow': typeof DataFlowRoute
  '/guide': typeof GuideRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/reconciliation': typeof ReconciliationRoute
  '/sites/$id': typeof SitesIdRoute
  '/sites': typeof SitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRoute
  '/data': typeof DataRoute
  '/data-flow': typeof DataFlowRoute
  '/guide': typeof GuideRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/reconciliation': typeof ReconciliationRoute
  '/sites': typeof SitesRouteWithChildren
  '/sites/$id': typeof SitesIdRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api'
    | '/data'
    | '/data-flow'
    | '/guide'
    | '/learn'
    | '/map'
    | '/reconciliation'
    | '/sites'
    | '/sites/$id'
    | '/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api'
    | '/data'
    | '/data-flow'
    | '/guide'
    | '/learn'
    | '/map'
    | '/reconciliation'
    | '/sites/$id'
    | '/sites'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api'
    | '/data'
    | '/data-flow'
    | '/guide'
    | '/learn'
    | '/map'
    | '/reconciliation'
    | '/sites'
    | '/sites/$id'
    | '/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiRoute: typeof ApiRoute
  DataRoute: typeof DataRoute
  DataFlowRoute: typeof DataFlowRoute
  GuideRoute: typeof GuideRoute
  LearnRoute: typeof LearnRoute
  MapRoute: typeof MapRoute
  ReconciliationRoute: typeof ReconciliationRoute
  SitesRoute: typeof SitesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-flow': {
      id: '/data-flow'
      path: '/data-flow'
      fullPath: '/data-flow'
      preLoaderRoute: typeof DataFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof SitesRoute
    }
    '/sites/$id': {
      id: '/sites/$id'
      path: '/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof SitesIdRouteImport
      parentRoute: typeof SitesRoute
    }
  }
}

interface SitesRouteChildren {
  SitesIdRoute: typeof SitesIdRoute
  SitesIndexRoute: typeof SitesIndexRoute
}

const SitesRouteChildren: SitesRouteChildren = {
  SitesIdRoute: SitesIdRoute,
  SitesIndexRoute: SitesIndexRoute,
}

const SitesRouteWithChildren = SitesRoute._addFileChildren(SitesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiRoute: ApiRoute,
  DataRoute: DataRoute,
  DataFlowRoute: DataFlowRoute,
  GuideRoute: GuideRoute,
  LearnRoute: LearnRoute,
  MapRoute: MapRoute,
  ReconciliationRoute: ReconciliationRoute,
  SitesRoute: SitesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
